services:
  postgres:
    image: postgres:18
    container_name: test_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    container_name: test_api
    working_dir: /app/TestTask
    volumes:
      - .:/app
    ports:
      - "8090:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=testdb;Username=postgres;Password=postgres"
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "dotnet run"

  pgadmin:
    image: dpage/pgadmin4
    container_name: test_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
  pgadmin_data: